### PR TITLE
wesnoth: upgrade 1.14.4 -> 1.14.4

### PR DESCRIPTION
**Pull request by schnitzeltony**
This fixes build with boost  1.69.0:

| <...>/wesnoth-1.14.4/src/units/frame.cpp:775:103: error: cannot convert 'boost::logic::tribool' to 'const bool' i

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>

### CODE REVIEW

**Comment by cazfi** [comment]
Subject line is wrong. Should be update to 1.14.6.

**Comment by schnitzeltony** [comment]
Yes right will do in a few minutes and append a fix for pingus either.
